version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cyronite
      POSTGRES_PASSWORD: password
      POSTGRES_DB: movie_booking
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
